// flow-typed signature: 919d721ee788421f5bcc11c26177d34d
// flow-typed version: <<STUB>>/npm-release_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'npm-release/index' {
  declare module.exports: $Exports<'npm-release'>;
}
declare module 'npm-release/index.js' {
  declare module.exports: $Exports<'npm-release'>;
}
